# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-02 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField()),
                ('phone', models.CharField(default='', max_length=20)),
                ('account_set', models.IntegerField(default=0)),
            ],
        ),
    ]
