# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mail_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='mail_verifier',
            field=models.IntegerField(default=0),
        ),
    ]
