# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_day', models.CharField(max_length=30)),
                ('json_data', models.CharField(max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=60)),
                ('nick', models.CharField(max_length=160)),
                ('order_id', models.CharField(max_length=30)),
                ('day_time', models.DateTimeField()),
                ('day_stamp', models.BigIntegerField()),
                ('insert_time', models.DateTimeField()),
                ('channel', models.CharField(max_length=60)),
                ('good_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('json_data', models.CharField(max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField()),
                ('login_user', models.CharField(default='', max_length=16)),
                ('record_data', models.CharField(default='', max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='GoodCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelID', models.CharField(max_length=36)),
                ('goodID', models.CharField(max_length=36)),
                ('cost', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='LimitGoodId',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LimitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.CharField(max_length=30)),
                ('channel', models.CharField(max_length=16)),
                ('good_type', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('json_data', models.CharField(max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='LimitPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.CharField(max_length=10)),
                ('pic_path', models.ImageField(upload_to='limit_time_shop/')),
                ('pic_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField()),
                ('login_user', models.CharField(default='', max_length=16)),
                ('record_data', models.CharField(default='', max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='SetCardsClose',
            fields=[
                ('card_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField(null=True)),
                ('card_number', models.CharField(db_index=True, max_length=60, null=True, unique=True)),
                ('card_secret', models.CharField(db_index=True, max_length=60, null=True, unique=True)),
                ('card_type', models.CharField(max_length=100, null=True)),
                ('card_price', models.CharField(max_length=100, null=True)),
                ('good_id', models.CharField(default='', max_length=30)),
                ('player_id', models.CharField(max_length=100, null=True)),
                ('player_nick', models.CharField(max_length=300, null=True)),
                ('player_phone', models.CharField(max_length=60, null=True)),
                ('change_time', models.DateTimeField(null=True)),
                ('change_state', models.IntegerField(choices=[(1, '\u5df2\u5151\u6362'), (2, '\u672a\u5151\u6362')], default=2, null=True)),
            ],
        ),
    ]
