# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-04 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_type', models.CharField(max_length=10)),
                ('broadcast_id', models.BigIntegerField()),
                ('day_time', models.BigIntegerField()),
                ('json_data', models.CharField(max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField()),
                ('login_user', models.CharField(default='', max_length=16)),
                ('record_data', models.CharField(default='', max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='EarlyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField()),
                ('login_user', models.CharField(default='', max_length=16)),
                ('record_data', models.CharField(default='', max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='EarlyWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.IntegerField(null=True)),
                ('user_list', models.CharField(max_length=600, null=True)),
                ('user_length', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(null=True)),
                ('nType', models.IntegerField()),
                ('sender', models.CharField(max_length=20, null=True)),
                ('recipients', models.CharField(max_length=20, null=True)),
                ('subject', models.CharField(max_length=16)),
                ('reason', models.CharField(max_length=80)),
                ('reward', models.CharField(max_length=1000)),
                ('status', models.BigIntegerField()),
                ('verifier', models.CharField(max_length=20, null=True)),
                ('verifier_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField()),
                ('login_user', models.CharField(default='', max_length=16)),
                ('record_data', models.CharField(default='', max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='OrderQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.DateTimeField()),
                ('insert_time', models.DateTimeField()),
                ('order_id', models.CharField(max_length=60)),
                ('productId', models.CharField(max_length=90)),
                ('user_id', models.CharField(max_length=12)),
                ('pay_total', models.CharField(default='', max_length=10)),
                ('pay_status', models.CharField(max_length=10)),
                ('channel', models.CharField(max_length=12)),
                ('json_data', models.CharField(max_length=1600)),
            ],
        ),
    ]
