# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.DateTimeField()),
                ('insert_time', models.DateTimeField()),
                ('channel', models.CharField(max_length=12)),
                ('json_data', models.CharField(max_length=16000)),
            ],
        ),
    ]
