# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.DateTimeField()),
                ('insert_time', models.DateTimeField()),
                ('channel', models.CharField(max_length=12)),
                ('json_data', models.CharField(max_length=16000)),
            ],
        ),
    ]
